[log]
  level = "DEBUG"
  format = "json"
# [providers.ecs]
#   exposedByDefault = false
#   cluster = ["pilotco-test-Cluster-7AcBdNOcTLpu"]
[providers]
  [providers.file]
    filename = "/etc/traefik/services.toml"
[entryPoints]
  [entryPoints.web]
    address = ":443"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.websecure.http.tls]
    certResolver = "biggaCertResolver"

[certificatesResolvers.biggaCertResolver.acme]
  email = "dhilip@reckonsys.com"
  storage = "/etc/traefik/acme/acme.json"
  [certificatesResolvers.biggaCertResolver.acme.dnsChallenge]
    provider = "digitalocean"
